CREATE SCHEMA IF NOT EXISTS Pruebas;

USE Pruebas;

CREATE TABLE IF NOT EXISTS ST_BAREAN_TEMP(
  ART char(20) COLLATE latin1_general_ci NOT NULL DEFAULT '0' COMMENT 'CODIGO DE ARTICULO',
  EAN varchar(20) COLLATE latin1_general_ci NOT NULL DEFAULT '' COMMENT 'CODIGO DE EAN',
  PRIMARY KEY (ART,EAN)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci COMMENT='TABLA TEMPORAL PARA INSERT/UPDATE MASIVO DE CODIGOS EAN';

CREATE TABLE ST_BAREAN(
  ART char(20) COLLATE latin1_general_ci NOT NULL DEFAULT '0' COMMENT 'CODIGO DE ARTICULO',
  EAN varchar(20) COLLATE latin1_general_ci NOT NULL DEFAULT '' COMMENT 'CODIGO DE EAN',
  FECM datetime NOT NULL DEFAULT now(),
  USRM varchar(20) NOT NULL DEFAULT 'enia',
  PRIMARY KEY (ART,EAN)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci COMMENT='CODIGOS EAN';

CREATE TABLE ST_ARTICULO(
  ID char(20) COLLATE latin1_general_ci NOT NULL DEFAULT '0' COMMENT 'CODIGO DE ARTICULO',
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS ST_BAREAN_TEMP;